if (USE_KRISP_DYNAMIC_LIBRARY)
	set(KRISP_THIRDPARTY_LIBS)
else()
	if(NOT DEFINED KRISP_3PARTY_LIB_DIR)
		message(FATAL_ERROR "KRISP_3PARTY_LIB_DIR is not defined")
	endif()
	set(EXTERNAL_LIBS
		libonnxruntime_session.a
		libonnxruntime_optimizer.a
		libonnxruntime_providers.a
		libonnxruntime_framework.a
		libonnxruntime_graph.a
		libonnxruntime_util.a
		libonnxruntime_mlas.a
		libonnxruntime_common.a
		libonnxruntime_flatbuffers.a
		libonnx.a
		libonnx_proto.a
		libprotoc.a
		libprotobuf.a
		libz.a
		libre2.a
		libabsl_base.a
		libabsl_scoped_set_env.a
		libabsl_failure_signal_handler.a
		libabsl_leak_check.a
		libabsl_flags_parse.a
		libabsl_flags_usage.a
		libabsl_flags_usage_internal.a
		libabsl_log_internal_check_op.a
		libabsl_die_if_null.a
		libabsl_log_flags.a
		libabsl_flags_reflection.a
		libabsl_raw_hash_set.a
		libabsl_hashtablez_sampler.a
		libabsl_flags_private_handle_accessor.a
		libabsl_flags_internal.a
		libabsl_flags_config.a
		libabsl_flags_program_name.a
		libabsl_flags_marshalling.a
		libabsl_flags_commandlineflag.a
		libabsl_flags_commandlineflag_internal.a
		libabsl_log_initialize.a
		libabsl_log_internal_conditions.a
		libabsl_log_internal_message.a
		libabsl_examine_stack.a
		libabsl_log_internal_format.a
		libabsl_log_internal_proto.a
		libabsl_log_internal_nullguard.a
		libabsl_log_internal_log_sink_set.a
		libabsl_log_internal_globals.a
		libabsl_log_globals.a
		libabsl_hash.a
		libabsl_city.a
		libabsl_low_level_hash.a
		libabsl_log_sink.a
		libabsl_log_entry.a
		libabsl_vlog_config_internal.a
		libabsl_log_internal_fnmatch.a
		libabsl_periodic_sampler.a
		libabsl_random_distributions.a
		libabsl_random_seed_sequences.a
		libabsl_random_internal_pool_urbg.a
		libabsl_random_seed_gen_exception.a
		libabsl_random_internal_seed_material.a
		libabsl_random_internal_randen.a
		libabsl_bad_any_cast_impl.a
		libabsl_bad_optional_access.a
		libabsl_bad_variant_access.a
		libabsl_civil_time.a
		libabsl_cord.a
		libabsl_cord_internal.a
		libabsl_cordz_functions.a
		libabsl_cordz_handle.a
		libabsl_cordz_info.a
		libabsl_cordz_sample_token.a
		libabsl_crc32c.a
		libabsl_crc_cord_state.a
		libabsl_crc_cpu_detect.a
		libabsl_crc_internal.a
		libabsl_debugging_internal.a
		libabsl_demangle_internal.a
		libabsl_exponential_biased.a
		libabsl_graphcycles_internal.a
		libabsl_int128.a
		libabsl_kernel_timeout_internal.a
		libabsl_log_severity.a
		libabsl_malloc_internal.a
		libabsl_random_internal_distribution_test_util.a
		libabsl_random_internal_platform.a
		libabsl_random_internal_randen_hwaes.a
		libabsl_random_internal_randen_hwaes_impl.a
		libabsl_random_internal_randen_slow.a
		libabsl_raw_logging_internal.a
		libabsl_spinlock_wait.a
		libabsl_stacktrace.a
		libabsl_status.a
		libabsl_statusor.a
		libabsl_str_format_internal.a
		libabsl_strerror.a
		libabsl_string_view.a
		libabsl_strings.a
		libabsl_strings_internal.a
		libabsl_symbolize.a
		libabsl_synchronization.a
		libabsl_throw_delegate.a
		libabsl_time.a
		libabsl_time_zone.a
		libflatbuffers.a
		libnsync.a
		libnsync_cpp.a
		libcpuinfo.a
		libcrypto.a
		libopenblas.a
		libresample.a
		libssl.a
	)
	set(KRISP_THIRDPARTY_LIBS)
	foreach(lib ${EXTERNAL_LIBS})
		list(APPEND KRISP_THIRDPARTY_LIBS "${KRISP_3PARTY_LIB_DIR}/${lib}")
	endforeach()
	list(APPEND KRISP_THIRDPARTY_LIBS -pthread -ldl)
endif()
