if (USE_KRISP_DYNAMIC_LIBRARY)
	set(KRISP_THIRDPARTY_LIBS)
else()
	if(NOT DEFINED KRISP_3PARTY_LIB_DIR)
		message(FATAL_ERROR "KRISP_3PARTY_LIB_DIR is not defined")
	endif()
	file(GLOB ALL_EXTERNAL_LIBS "${KRISP_3PARTY_LIB_DIR}/*.a" "${KRISP_3PARTY_LIB_DIR}/*.dylib")
	set(KRISP_THIRDPARTY_LIBS 
		${ALL_EXTERNAL_LIBS}
	)
endif()

list(APPEND KRISP_THIRDPARTY_LIBS blas)
