if (${CMAKE_SYSTEM_PROCESSOR} MATCHES ".*(arm|ARM).*")
	message(STATUS "ARM CPU is used")
	target_link_libraries(${APPNAME_NC} blas)
	target_link_libraries(${DLLNAME} blas)
else()
	include(mkl.cmake)
endif()
